services:
  caddy:
    image: caddy:alpine
    container_name: caddy
    restart: always
    networks:
      - reverse_proxy
    volumes:
      - ./domain-config:/domain-config
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy_data:/data
      - ./caddy_config:/config
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
      
networks:
  reverse_proxy:
    driver: "bridge"
    name: reverse_proxy
